2025-05-09 21:00:16,763 INFO    MainThread:22840 [wandb_init.py:setup_run_log_directory():724] Logging user logs to D:\Deep_learning\wandb\run-20250509_210016-lx7fzlw7\logs\debug.log
2025-05-09 21:00:16,763 INFO    MainThread:22840 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to D:\Deep_learning\wandb\run-20250509_210016-lx7fzlw7\logs\debug-internal.log
2025-05-09 21:00:16,763 INFO    MainThread:22840 [wandb_init.py:init():852] calling init triggers
2025-05-09 21:00:16,763 INFO    MainThread:22840 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'batch_size': 64, 'optimizer': 'adam', 'epochs': 5050, '_wandb': {}}
2025-05-09 21:00:18,450 INFO    MainThread:22840 [wandb_init.py:init():893] starting backend
2025-05-09 21:00:18,450 INFO    MainThread:22840 [wandb_init.py:init():897] sending inform_init request
2025-05-09 21:00:18,452 INFO    MainThread:22840 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-05-09 21:00:18,455 INFO    MainThread:22840 [wandb_init.py:init():907] backend started and connected
2025-05-09 21:00:18,456 INFO    MainThread:22840 [wandb_init.py:init():1005] updated telemetry
2025-05-09 21:00:18,497 INFO    MainThread:22840 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-09 21:00:19,738 INFO    MainThread:22840 [wandb_init.py:init():1104] starting run threads in backend
2025-05-09 21:00:19,951 INFO    MainThread:22840 [wandb_run.py:_console_start():2573] atexit reg
2025-05-09 21:00:19,951 INFO    MainThread:22840 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-09 21:00:19,951 INFO    MainThread:22840 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-09 21:00:19,951 INFO    MainThread:22840 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-09 21:00:19,952 INFO    MainThread:22840 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-09 21:15:30,240 INFO    MsgRouterThr:22840 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
